### ISSUE TITLE
How to hide footer

### ISSUE THREAD

**Issue by jiangheng90** [votetake/vue-unity-webgl#15]
I found your template has a footer contains fullscreen bottom.
how can i remove it. I have saw your sourcecode, I modefy your Unity.vue file it seems doesnot work.

**Comment by votetake** [comment]
You must add property `hideFooter=true`

Example
```
<template>
  <unity src="static/Build/game.json" width="1000" height="600" unityLoader="static/Build/UnityLoader.js" hideFooter=true></unity>  
</template>
```
