### ISSUE TITLE
calling vue js function from unity

### ISSUE THREAD

**Issue by akbarism** [votetake/vue-unity-webgl#26]
can unity call the function in vue js?
so I have a case where when the game is finished, vue knows that and runs the function,

**Comment by KennyTech** [comment]
HELP DID YOU FIGURE IT OUT?

**Comment by votetake** [comment]
Documentation on Unity Portal [WebGL: Interacting with browser scripting](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html)

TL;DR: anywhere in your application, you can declare functions that Unity will then call. Example declare on `created` or `mounted` methods and when call it from Unity
```
created() {
    window.gameFinished = function () {
        console.info('window.gameFinished');
    }
}
```

**Comment by votetake** [comment]
Or see @bondythegreat [comment](https://github.com/votetake/vue-unity-webgl/issues/7#issuecomment-794028383) in a similar issue
