### ISSUE TITLE
Messages from unity to js

### ISSUE THREAD

**Issue by tayursky** [votetake/vue-unity-webgl#32]
Hi, how can I accept a message from unity?

**Comment by votetake** [comment]
> Hi, how can I accept a message from unity?

Hi, have you read threads #26 and #7?

**Comment by tayursky** [comment]
I get a function without arguments
```
created() {
    window.gameFinished = function (args) {
        console.info('window.gameFinished', args);
    }
}
```

In console:
`gameFinished undefined`

**Comment by votetake** [comment]
Have you looked at the documentation at Unity? 

https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html

**Comment by tayursky** [comment]
Yes I did )

**Comment by tayursky** [comment]
Yes I looked )

I did it this way and all worked:
ConfiguratorEvent.js
```
class ConfiguratorEvent {
  constructor () {
    this.callbacks = []
  }

  call (arg) {
    for (let i = 0; i < this.callbacks.length; i++) {
      this.callbacks[i](arg)
    }
  }

  addListener (callback) {
    this.callbacks.push(callback)
  }
}

export default ConfiguratorEvent
```
file.vue
```
import ConfiguratorEvent from '@/assets/ConfiguratorEvent.js'

  created () {
    if (process.client) {
      window.gameFinished = new ConfiguratorEvent()
      window.gameFinished.addListener(arg => console.log('gameFinished:', arg))
    }
  },
```
process.client - because I use .nuxt

**Comment by votetake** [comment]
Are you sure the Unity function calls window.gameFinished with arguments?

**Comment by tayursky** [comment]
I do not know C# / unity, my side is only js. And yes now I get the argument.

**Comment by votetake** [comment]
Has the problem been resolved?
