### ISSUE TITLE
Calling JavaScript functions in Vue from Unity scripts

### ISSUE THREAD

**Issue by alex83130** [votetake/vue-unity-webgl#7]
Hi,
I need to calling a function in my vue component from Unity scripts. What is the best way to do that?
Here, there is a exemple with React: https://npm.taobao.org/package/react-native-unity-webgl

If you know a solution to do the same thing in Vue ...

Thanks in advance.

**Comment by akbarism** [comment]
anyone please?

**Comment by votetake** [comment]
#26

**Comment by votetake** [comment]
I also wrote an example in #26
